server:
  port: 8101

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  security:
    user:
      #password: ${CONFIG_SERVICE_PASSWORD}
      # Values for local testing:
      password: sesame