logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://registry:8102/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:8103/uaa/users/current