server:
  servlet:
    context-path: /uaa
  port: 8103

spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: turtech
      port: 27017