server:
  port: 9000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-mills: 20000
    socket-timeout-millis: 20000

routes:
  auth-service:
    path: /uaa/**
    url: http://auth-service:8103
    stripPrefix: false
    sensitiveHeaders:

  account-service:
    path: /accounts/**
    serviceId: account-service
    stripPrefix: false
    sensitiveHeaders: