keycloak:
  auth-server-url: http://localhost:8103/auth
  realm: turtech
  resource: turtech-login
  public-client: true
  principal-attribute: preffered_username

spring:
  redis:
    host: localhost
    #database:
    port: 6379
    #password:

server:
  port: 8113