export const GET_ERRORS = "GET_ERRORS";

// Types for PRODUCT ACTIONS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";

// Types for USER REVIEW ACTIONS
export const GET_REVIEWS = "GET_REVIEWS";
export const LEAVE_REVIEW = "LEAVE_REVIEW";

// Types for SHOPPING CART ACTIONS
export const GET_CART = "GET_CART";
export const ADD_TO_CART = "ADD_TO_CART";

// Types for USER PROFILE ACTIONS
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PAYMENT = "GET_USER_PAYMENT";
export const GET_USER_SHIPPING = "GET_USER_SHIPPING";
export const GET_USER_ORDERS = "GET_USER_ORDERS";

// Types for SECURITY ACTIONS
export const SET_CURRENT_USER = "SET_CURRENT_USER";