export const GET_ERRORS = "GET_ERRORS";

// Types for PRODUCT ACTIONS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";

// Types for USER REVIEW ACTIONS
export const GET_REVIEWS = "GET_REVIEWS";
export const LEAVE_REVIEW = "LEAVE_REVIEW";

// Types for SHOPPING CART ACTIONS
export const GET_CART = "GET_CART";
export const ADD_TO_CART = "ADD_TO_CART";

// Types for USER PROFILE ACTIONS
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PAYMENT_OPTIONS = "GET_USER_PAYMENT_OPTIONS";
export const GET_USER_PAYMENT_OPTION = "GET_USER_PAYMENT_OPTION";
export const ADD_USER_PAYMENT_OPTION = "ADD_USER_PAYMENT_OPTION";
export const UPDATE_USER_PAYMENT_OPTION = "UPDATE_USER_PAYMENT_OPTION";
export const REMOVE_USER_PAYMENT_OPTION = "REMOVE_USER_PAYMENT_OPTION";
export const SET_DEFAULT_USER_PAYMENT_OPTION = "SET_DEFAULT_USER_PAYMENT_OPTION";
export const GET_USER_BILLING_ADDRESS = "GET_USER_BILLING_ADDRESS";
export const GET_USER_SHIPPING_ADDRESSES = "GET_USER_SHIPPING_ADDRESSES";
export const GET_USER_SHIPPING_ADDRESS = "GET_USER_SHIPPING_ADDRESS";
export const ADD_USER_SHIPPING_ADDRESS = "ADD_USER_SHIPPING_ADDRESS";
export const UPDATE_USER_SHIPPING_ADDRESS = "UPDATE_USER_SHIPPING_ADDRESS";
export const REMOVE_USER_SHIPPING_ADDRESS = "REMOVE_USER_SHIPPING_ADDRESS";
export const SET_DEFAULT_USER_SHIPPING_ADDRESS = "SET_DEFAULT_USER_SHIPPING_ADDRESS";
export const GET_USER_ORDERS = "GET_USER_ORDERS";
export const GET_USER_ORDER_DETAILS = "GET_USER_ORDER_DETAILS";
export const GET_CART_ITEM_LIST_BY_ORDER_ID = "GET_CART_ITEM_LIST_BY_ORDER_ID";

// Types for SECURITY ACTIONS
export const SET_CURRENT_USER = "SET_CURRENT_USER";