export const GET_ERRORS = "GET_ERRORS";

// Types for PRODUCT ACTIONS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";

// Types for USER REVIEW ACTIONS
export const GET_REVIEWS = "GET_REVIEWS";
export const LEAVE_REVIEW = "LEAVE_REVIEW";

// Types for SHOPPING CART ACTIONS
export const GET_CART = "GET_CART";
export const ADD_TO_CART = "ADD_TO_CART";

// Types for USER PROFILE ACTIONS
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PAYMENT = "GET_USER_PAYMENT";
export const ADD_USER_PAYMENT = "ADD_USER_PAYMENT";
export const UPDATE_USER_PAYMENT = "UPDATE_USER_PAYMENT";
export const REMOVE_USER_PAYMENT = "REMOVE_USER_SHIPPING";
export const SET_DEFAULT_USER_PAYMENT = "SET_DEFAULT_USER_PAYMENT";
export const GET_USER_SHIPPING = "GET_USER_SHIPPING";
export const ADD_USER_SHIPPING = "ADD_USER_SHIPPING";
export const UPDATE_USER_SHIPPING = "UPDATE_USER_SHIPPING";
export const REMOVE_USER_SHIPPING = "REMOVE_USER_SHIPPING";
export const SET_DEFAULT_USER_SHIPPING = "SET_DEFAULT_USER_SHIPPING";
export const GET_USER_ORDERS = "GET_USER_ORDERS";
export const GET_USER_ORDER = "GET_USER_ORDER";
export const GET_CART_ITEM_LIST_BY_ORDER_ID = "GET_CART_ITEM_LIST_BY_ORDER_ID";

// Types for SECURITY ACTIONS
export const SET_CURRENT_USER = "SET_CURRENT_USER";